import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "./components/navbar/Navbar";
import { MainSect } from "./components/MainSect";
import Prices from "./components/Prices";
import { Referral } from "./components/Referral";
import { FeaturesSect } from "./components/FeaturesSect";
import { TestimonialsSect } from "./components/TestimonialsSect";
import { Explore } from "./components/Explore";
import { Footer } from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MainSect />
        <Prices />
        <Referral />
        <FeaturesSect />
        <TestimonialsSect />
        <Explore />
        <Footer />
        {children}
      </body>
    </html>
  );
}
